# Generated by Django 3.1.12 on 2025-07-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_service_provider',
            new_name='is_serviceprovider',
        ),
        migrations.AddField(
            model_name='service',
            name='provider_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
