# Generated by Django 3.1.12 on 2025-07-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='services',
        ),
        migrations.CreateModel(
            name='ServiceProviderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_links', to='api.service')),
                ('serviceprovider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='api.serviceprovider')),
            ],
            options={
                'unique_together': {('serviceprovider', 'service')},
            },
        ),
    ]
